site_name: HSTools
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands: commands.md
  - Examples: examples.md
  - Reference: reference.md
  - Contributing: contributing.md
  - About: about.md
theme: readthedocs
